# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mark.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormMark(object):
    def setupUi(self, FormMark):
        FormMark.setObjectName("FormMark")
        FormMark.resize(622, 626)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormMark)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_7 = QtWidgets.QHBoxLayout()
        self.layout_7.setObjectName("layout_7")
        self.btn_open = QtWidgets.QPushButton(FormMark)
        self.btn_open.setObjectName("btn_open")
        self.layout_7.addWidget(self.btn_open)
        self.btn_save = QtWidgets.QPushButton(FormMark)
        self.btn_save.setObjectName("btn_save")
        self.layout_7.addWidget(self.btn_save)
        self.btn_gencsv = QtWidgets.QPushButton(FormMark)
        self.btn_gencsv.setObjectName("btn_gencsv")
        self.layout_7.addWidget(self.btn_gencsv)
        self.verticalLayout.addLayout(self.layout_7)
        self.lab_info = QtWidgets.QLabel(FormMark)
        self.lab_info.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_info.setObjectName("lab_info")
        self.verticalLayout.addWidget(self.lab_info)
        self.layout_2 = QtWidgets.QHBoxLayout()
        self.layout_2.setObjectName("layout_2")
        self.btn_back = QtWidgets.QPushButton(FormMark)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back.sizePolicy().hasHeightForWidth())
        self.btn_back.setSizePolicy(sizePolicy)
        self.btn_back.setObjectName("btn_back")
        self.layout_2.addWidget(self.btn_back)
        self.btn_yes = QtWidgets.QPushButton(FormMark)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_yes.sizePolicy().hasHeightForWidth())
        self.btn_yes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_yes.setFont(font)
        self.btn_yes.setStyleSheet("")
        self.btn_yes.setObjectName("btn_yes")
        self.layout_2.addWidget(self.btn_yes)
        self.btn_no = QtWidgets.QPushButton(FormMark)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_no.sizePolicy().hasHeightForWidth())
        self.btn_no.setSizePolicy(sizePolicy)
        self.btn_no.setObjectName("btn_no")
        self.layout_2.addWidget(self.btn_no)
        self.btn_next = QtWidgets.QPushButton(FormMark)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next.sizePolicy().hasHeightForWidth())
        self.btn_next.setSizePolicy(sizePolicy)
        self.btn_next.setObjectName("btn_next")
        self.layout_2.addWidget(self.btn_next)
        self.verticalLayout.addLayout(self.layout_2)
        self.layout_1 = QtWidgets.QGridLayout()
        self.layout_1.setObjectName("layout_1")
        self.radio_1 = QtWidgets.QRadioButton(FormMark)
        self.radio_1.setObjectName("radio_1")
        self.layout_1.addWidget(self.radio_1, 0, 0, 1, 1)
        self.radio_3 = QtWidgets.QRadioButton(FormMark)
        self.radio_3.setObjectName("radio_3")
        self.layout_1.addWidget(self.radio_3, 1, 0, 1, 1)
        self.radio_2 = QtWidgets.QRadioButton(FormMark)
        self.radio_2.setObjectName("radio_2")
        self.layout_1.addWidget(self.radio_2, 0, 1, 1, 1)
        self.radio_4 = QtWidgets.QRadioButton(FormMark)
        self.radio_4.setObjectName("radio_4")
        self.layout_1.addWidget(self.radio_4, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.layout_1)
        self.layout_8 = QtWidgets.QHBoxLayout()
        self.layout_8.setObjectName("layout_8")
        self.label_static0 = QtWidgets.QLabel(FormMark)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_static0.sizePolicy().hasHeightForWidth())
        self.label_static0.setSizePolicy(sizePolicy)
        self.label_static0.setMinimumSize(QtCore.QSize(50, 0))
        self.label_static0.setBaseSize(QtCore.QSize(0, 0))
        self.label_static0.setObjectName("label_static0")
        self.layout_8.addWidget(self.label_static0)
        self.text_word = QtWidgets.QLineEdit(FormMark)
        self.text_word.setObjectName("text_word")
        self.layout_8.addWidget(self.text_word)
        self.verticalLayout.addLayout(self.layout_8)
        self.layout_6 = QtWidgets.QHBoxLayout()
        self.layout_6.setObjectName("layout_6")
        self.label_static1 = QtWidgets.QLabel(FormMark)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_static1.sizePolicy().hasHeightForWidth())
        self.label_static1.setSizePolicy(sizePolicy)
        self.label_static1.setMinimumSize(QtCore.QSize(50, 0))
        self.label_static1.setBaseSize(QtCore.QSize(0, 0))
        self.label_static1.setObjectName("label_static1")
        self.layout_6.addWidget(self.label_static1)
        self.text_title = QtWidgets.QLineEdit(FormMark)
        self.text_title.setObjectName("text_title")
        self.layout_6.addWidget(self.text_title)
        self.verticalLayout.addLayout(self.layout_6)
        self.layout_3 = QtWidgets.QHBoxLayout()
        self.layout_3.setObjectName("layout_3")
        self.label_static2 = QtWidgets.QLabel(FormMark)
        self.label_static2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_static2.setObjectName("label_static2")
        self.layout_3.addWidget(self.label_static2)
        self.text_uid = QtWidgets.QLineEdit(FormMark)
        self.text_uid.setReadOnly(True)
        self.text_uid.setObjectName("text_uid")
        self.layout_3.addWidget(self.text_uid)
        self.verticalLayout.addLayout(self.layout_3)
        self.layout_4 = QtWidgets.QHBoxLayout()
        self.layout_4.setObjectName("layout_4")
        self.label_static3 = QtWidgets.QLabel(FormMark)
        self.label_static3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_static3.setObjectName("label_static3")
        self.layout_4.addWidget(self.label_static3)
        self.text_freq = QtWidgets.QLineEdit(FormMark)
        self.text_freq.setReadOnly(True)
        self.text_freq.setObjectName("text_freq")
        self.layout_4.addWidget(self.text_freq)
        self.verticalLayout.addLayout(self.layout_4)
        self.layout_5 = QtWidgets.QHBoxLayout()
        self.layout_5.setObjectName("layout_5")
        self.label_static4 = QtWidgets.QLabel(FormMark)
        self.label_static4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_static4.setObjectName("label_static4")
        self.layout_5.addWidget(self.label_static4)
        self.text_words = QtWidgets.QLineEdit(FormMark)
        self.text_words.setReadOnly(True)
        self.text_words.setObjectName("text_words")
        self.layout_5.addWidget(self.text_words)
        self.verticalLayout.addLayout(self.layout_5)
        self.text_title_1 = QtWidgets.QLineEdit(FormMark)
        self.text_title_1.setReadOnly(True)
        self.text_title_1.setObjectName("text_title_1")
        self.verticalLayout.addWidget(self.text_title_1)
        self.text_detail_1 = QtWidgets.QTextEdit(FormMark)
        self.text_detail_1.setReadOnly(True)
        self.text_detail_1.setObjectName("text_detail_1")
        self.verticalLayout.addWidget(self.text_detail_1)
        self.text_title_2 = QtWidgets.QLineEdit(FormMark)
        self.text_title_2.setReadOnly(True)
        self.text_title_2.setObjectName("text_title_2")
        self.verticalLayout.addWidget(self.text_title_2)
        self.text_detail_2 = QtWidgets.QTextEdit(FormMark)
        self.text_detail_2.setReadOnly(True)
        self.text_detail_2.setObjectName("text_detail_2")
        self.verticalLayout.addWidget(self.text_detail_2)
        self.text_title_3 = QtWidgets.QLineEdit(FormMark)
        self.text_title_3.setReadOnly(True)
        self.text_title_3.setObjectName("text_title_3")
        self.verticalLayout.addWidget(self.text_title_3)
        self.text_detail_3 = QtWidgets.QTextEdit(FormMark)
        self.text_detail_3.setReadOnly(True)
        self.text_detail_3.setObjectName("text_detail_3")
        self.verticalLayout.addWidget(self.text_detail_3)

        self.retranslateUi(FormMark)
        QtCore.QMetaObject.connectSlotsByName(FormMark)
        FormMark.setTabOrder(self.btn_open, self.btn_save)
        FormMark.setTabOrder(self.btn_save, self.btn_gencsv)
        FormMark.setTabOrder(self.btn_gencsv, self.btn_back)
        FormMark.setTabOrder(self.btn_back, self.btn_yes)
        FormMark.setTabOrder(self.btn_yes, self.btn_no)
        FormMark.setTabOrder(self.btn_no, self.btn_next)
        FormMark.setTabOrder(self.btn_next, self.radio_1)
        FormMark.setTabOrder(self.radio_1, self.radio_2)
        FormMark.setTabOrder(self.radio_2, self.radio_3)
        FormMark.setTabOrder(self.radio_3, self.radio_4)
        FormMark.setTabOrder(self.radio_4, self.text_word)
        FormMark.setTabOrder(self.text_word, self.text_title)
        FormMark.setTabOrder(self.text_title, self.text_uid)
        FormMark.setTabOrder(self.text_uid, self.text_freq)
        FormMark.setTabOrder(self.text_freq, self.text_words)
        FormMark.setTabOrder(self.text_words, self.text_title_1)
        FormMark.setTabOrder(self.text_title_1, self.text_detail_1)
        FormMark.setTabOrder(self.text_detail_1, self.text_title_2)
        FormMark.setTabOrder(self.text_title_2, self.text_detail_2)
        FormMark.setTabOrder(self.text_detail_2, self.text_title_3)
        FormMark.setTabOrder(self.text_title_3, self.text_detail_3)

    def retranslateUi(self, FormMark):
        _translate = QtCore.QCoreApplication.translate
        FormMark.setWindowTitle(_translate("FormMark", "Form"))
        self.btn_open.setText(_translate("FormMark", "Open"))
        self.btn_save.setText(_translate("FormMark", "Save"))
        self.btn_gencsv.setText(_translate("FormMark", "GenCSV"))
        self.lab_info.setText(_translate("FormMark", "12/23"))
        self.btn_back.setText(_translate("FormMark", "<"))
        self.btn_yes.setText(_translate("FormMark", "Yes"))
        self.btn_no.setText(_translate("FormMark", "No"))
        self.btn_next.setText(_translate("FormMark", ">"))
        self.radio_1.setText(_translate("FormMark", "社会防疫动态"))
        self.radio_3.setText(_translate("FormMark", "专业知识科普"))
        self.radio_2.setText(_translate("FormMark", "大众防护指南"))
        self.radio_4.setText(_translate("FormMark", "抗击疫情故事"))
        self.label_static0.setText(_translate("FormMark", "word"))
        self.label_static1.setText(_translate("FormMark", "title"))
        self.label_static2.setText(_translate("FormMark", "uid"))
        self.label_static3.setText(_translate("FormMark", "freq"))
        self.label_static4.setText(_translate("FormMark", "words"))

