# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mark.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormMark(object):
    def setupUi(self, FormMark):
        FormMark.setObjectName("FormMark")
        FormMark.resize(622, 659)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormMark)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_7 = QtWidgets.QHBoxLayout()
        self.layout_7.setObjectName("layout_7")
        self.btn_open = QtWidgets.QPushButton(FormMark)
        self.btn_open.setObjectName("btn_open")
        self.layout_7.addWidget(self.btn_open)
        self.btn_save = QtWidgets.QPushButton(FormMark)
        self.btn_save.setObjectName("btn_save")
        self.layout_7.addWidget(self.btn_save)
        self.btn_gencsv = QtWidgets.QPushButton(FormMark)
        self.btn_gencsv.setObjectName("btn_gencsv")
        self.layout_7.addWidget(self.btn_gencsv)
        self.verticalLayout.addLayout(self.layout_7)
        self.lab_info = QtWidgets.QLabel(FormMark)
        self.lab_info.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_info.setObjectName("lab_info")
        self.verticalLayout.addWidget(self.lab_info)
        self.layout_2 = QtWidgets.QHBoxLayout()
        self.layout_2.setObjectName("layout_2")
        self.btn_back = QtWidgets.QPushButton(FormMark)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back.sizePolicy().hasHeightForWidth())
        self.btn_back.setSizePolicy(sizePolicy)
        self.btn_back.setObjectName("btn_back")
        self.layout_2.addWidget(self.btn_back)
        self.btn_next = QtWidgets.QPushButton(FormMark)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next.sizePolicy().hasHeightForWidth())
        self.btn_next.setSizePolicy(sizePolicy)
        self.btn_next.setObjectName("btn_next")
        self.layout_2.addWidget(self.btn_next)
        self.verticalLayout.addLayout(self.layout_2)
        self.layout_3 = QtWidgets.QHBoxLayout()
        self.layout_3.setObjectName("layout_3")
        self.btn_1_yes = QtWidgets.QPushButton(FormMark)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1_yes.sizePolicy().hasHeightForWidth())
        self.btn_1_yes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_1_yes.setFont(font)
        self.btn_1_yes.setStyleSheet("")
        self.btn_1_yes.setObjectName("btn_1_yes")
        self.layout_3.addWidget(self.btn_1_yes)
        self.btn_1_no = QtWidgets.QPushButton(FormMark)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1_no.sizePolicy().hasHeightForWidth())
        self.btn_1_no.setSizePolicy(sizePolicy)
        self.btn_1_no.setObjectName("btn_1_no")
        self.layout_3.addWidget(self.btn_1_no)
        self.verticalLayout.addLayout(self.layout_3)
        self.layout_4 = QtWidgets.QHBoxLayout()
        self.layout_4.setObjectName("layout_4")
        self.btn_2_yes = QtWidgets.QPushButton(FormMark)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2_yes.sizePolicy().hasHeightForWidth())
        self.btn_2_yes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_2_yes.setFont(font)
        self.btn_2_yes.setStyleSheet("")
        self.btn_2_yes.setObjectName("btn_2_yes")
        self.layout_4.addWidget(self.btn_2_yes)
        self.btn_2_no = QtWidgets.QPushButton(FormMark)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2_no.sizePolicy().hasHeightForWidth())
        self.btn_2_no.setSizePolicy(sizePolicy)
        self.btn_2_no.setObjectName("btn_2_no")
        self.layout_4.addWidget(self.btn_2_no)
        self.verticalLayout.addLayout(self.layout_4)
        self.layout_5 = QtWidgets.QHBoxLayout()
        self.layout_5.setObjectName("layout_5")
        self.btn_3_yes = QtWidgets.QPushButton(FormMark)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3_yes.sizePolicy().hasHeightForWidth())
        self.btn_3_yes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_3_yes.setFont(font)
        self.btn_3_yes.setStyleSheet("")
        self.btn_3_yes.setObjectName("btn_3_yes")
        self.layout_5.addWidget(self.btn_3_yes)
        self.btn_3_no = QtWidgets.QPushButton(FormMark)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3_no.sizePolicy().hasHeightForWidth())
        self.btn_3_no.setSizePolicy(sizePolicy)
        self.btn_3_no.setObjectName("btn_3_no")
        self.layout_5.addWidget(self.btn_3_no)
        self.verticalLayout.addLayout(self.layout_5)
        self.text_detail_1 = QtWidgets.QTextEdit(FormMark)
        self.text_detail_1.setReadOnly(True)
        self.text_detail_1.setPlaceholderText("")
        self.text_detail_1.setObjectName("text_detail_1")
        self.verticalLayout.addWidget(self.text_detail_1)
        self.text_detail_2 = QtWidgets.QTextEdit(FormMark)
        self.text_detail_2.setReadOnly(True)
        self.text_detail_2.setObjectName("text_detail_2")
        self.verticalLayout.addWidget(self.text_detail_2)

        self.retranslateUi(FormMark)
        QtCore.QMetaObject.connectSlotsByName(FormMark)
        FormMark.setTabOrder(self.btn_open, self.btn_save)
        FormMark.setTabOrder(self.btn_save, self.btn_gencsv)
        FormMark.setTabOrder(self.btn_gencsv, self.btn_back)
        FormMark.setTabOrder(self.btn_back, self.btn_next)
        FormMark.setTabOrder(self.btn_next, self.text_detail_1)
        FormMark.setTabOrder(self.text_detail_1, self.text_detail_2)

    def retranslateUi(self, FormMark):
        _translate = QtCore.QCoreApplication.translate
        FormMark.setWindowTitle(_translate("FormMark", "Form"))
        self.btn_open.setText(_translate("FormMark", "Open"))
        self.btn_save.setText(_translate("FormMark", "Save"))
        self.btn_gencsv.setText(_translate("FormMark", "GenCSV"))
        self.lab_info.setText(_translate("FormMark", "12/23"))
        self.btn_back.setText(_translate("FormMark", "<(&A)"))
        self.btn_next.setText(_translate("FormMark", ">(&D)"))
        self.btn_1_yes.setText(_translate("FormMark", "能生成注释(&7)"))
        self.btn_1_no.setText(_translate("FormMark", "不能生成注释(&8)"))
        self.btn_2_yes.setText(_translate("FormMark", "能生成代码(&4)"))
        self.btn_2_no.setText(_translate("FormMark", "不能生成代码(&5)"))
        self.btn_3_yes.setText(_translate("FormMark", "代码有问题(&1)"))
        self.btn_3_no.setText(_translate("FormMark", "代码没有问题(&2)"))

